In [27]:
# very important: https://www.analyticsvidhya.com/blog/2022/07/structuring-data-science-projects-workflow-beginners-guide/
# import dataset straight from sklearn
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression
import pandas as pd

**Data in Action**<br>
sklearn.utils.Bunch


In [12]:
iris = load_iris()

In [13]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [14]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [22]:
iris.target # 0->setosa, 1->versicolor, 2->virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [23]:
X = iris.data
y = iris.target
print(len(X), len(y))

150 150


In [33]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, train_size=0.7)

In [32]:
iris.data, iris.target

(array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
        [5

In [38]:
len(y_train), len(y_test), len(X_train), len(X_test)

(105, 45, 105, 45)

In [39]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [40]:
model.predict(X_test)

array([1, 1, 2, 2, 2, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0, 2, 2,
       1, 0, 0, 2, 1, 0, 0, 0, 2, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2, 0, 0, 2,
       1])

In [41]:
y_test

array([1, 1, 2, 2, 2, 0, 0, 2, 1, 1, 0, 0, 1, 1, 1, 0, 2, 0, 0, 0, 2, 2,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 2, 0, 2, 1, 1, 1, 2, 2, 2, 0, 0, 2,
       1])

In [42]:
model.score(X_test, y_test)

0.9555555555555556

In [72]:
#youtube: https://www.youtube.com/watch?v=gofilGC-vMk&ab_channel=NormalizedNerd
from pandas import DataFrame
import statsmodels.api as sm
data = {
    'month': [12,11,10,9,8,7,6,5,4],
    'free_time': [120,110,100,90,80,85,60,50,40],
    'num_videos': [8,8,7,6,6,7,6,4,5]
}
df = DataFrame(data)

X = df['free_time']
Y = df['num_videos']
X = sm.add_constant(X)

model = sm.OLS(Y, X).fit()
predictions = model.predict(X)

print_model = model.summary()
print(print_model)
predictions

                            OLS Regression Results                            
Dep. Variable:             num_videos   R-squared:                       0.818
Model:                            OLS   Adj. R-squared:                  0.792
Method:                 Least Squares   F-statistic:                     31.55
Date:                Sat, 03 Dec 2022   Prob (F-statistic):           0.000802
Time:                        20:11:50   Log-Likelihood:                -7.0819
No. Observations:                   9   AIC:                             18.16
Df Residuals:                       7   BIC:                             18.56
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.7345      0.672      4.072      0.0

/Users/bijayamanandhar/opt/anaconda3/lib/python3.8/site-packages/scipy/stats/stats.py:1603: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=9
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


0    8.022599
1    7.581921
2    7.141243
3    6.700565
4    6.259887
5    6.480226
6    5.378531
7    4.937853
8    4.497175
dtype: float64

In [95]:
#https://www.statsmodels.org/0.8.0/examples/notebooks/generated/ols.html
#https://www.statsmodels.org/stable/index.html
import numpy as np
nsample = 100
x = np.linspace(0, 10, 100)
X = np.column_stack((x, x**2))
beta = np.array([1, 0.1, 10])
e = np.random.normal(size=nsample)
e

array([ 1.23619498,  0.96765792, -0.04331266, -0.15163832,  1.50747326,
       -0.92560983, -0.26112419, -0.02386667, -1.12853556,  0.33879711,
        1.17499811, -1.84311356, -0.68045858,  1.21493843,  0.07285944,
        0.7661163 , -0.66393327,  1.06103252,  0.43651956,  0.59271994,
       -0.69218716, -1.12076261, -1.00826359, -1.21320404, -0.34208319,
        0.99848485,  0.46215047,  0.69329923, -0.19213521, -0.64973741,
       -0.79561447, -0.73557143, -0.21102663,  1.13980177, -0.19314536,
        1.83076234, -1.73354737,  0.63056369, -0.69947223,  1.60230365,
        0.50039905,  1.55660129, -0.9565015 , -0.71521324, -1.20659573,
        0.95043292, -0.05824894, -0.10929396, -0.99172223,  0.28684669,
       -0.77336354,  0.35890902, -1.84650051, -0.82026586,  1.5046379 ,
        0.60269115,  0.90181642, -0.7883478 ,  0.36425242, -0.1031092 ,
        0.12484863, -1.6802658 ,  0.53154966,  1.27337436, -1.015893  ,
        0.07203664, -0.82079678, -0.35731957, -1.2215823 , -0.24

In [96]:
[*range(0,101,25)] #python

[0, 25, 50, 75, 100]

In [99]:
np.arange(1,10) #numpy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])