<h3>Case Study</h3>
<p>I will be using the dataset directly imported from SKLearn library and build a multiclass classifier model using LogisticRegression Python classifier available in the open library.</p>

In [1]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [2]:
iris = load_iris()

In [3]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [4]:
iris.target # 0->setosa, 1->versicolor, 2->virginica

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
#count occurance of each class
x = iris.target
#    setosa                  versicolor              verginica 
np.count_nonzero(x==0), np.count_nonzero(x==1), np.count_nonzero(x==2)

(50, 50, 50)

In [7]:
type(iris.target)

numpy.ndarray

In [8]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
iris.data[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, train_size=0.7)

In [11]:
model = LogisticRegression(max_iter = 4000) 
model.fit(X_train, y_train)

LogisticRegression(max_iter=4000)

In [12]:
model.predict(X_test)

array([2, 1, 2, 2, 0, 2, 0, 0, 1, 2, 1, 2, 0, 0, 0, 2, 1, 0, 1, 1, 1, 1,
       1, 0, 2, 1, 0, 2, 0, 1, 1, 1, 2, 1, 2, 0, 0, 0, 2, 1, 1, 2, 0, 1,
       2])

In [13]:
model.score(X_test, y_test)

0.9777777777777777